#!/bin/sh
webpack --devtool source-map --colors

node_modules/.bin/uglifyjs dist/NexusUI.js \
  --output dist/NexusUI.min.js \
  --source-map dist/NexusUI.min.map \
  --source-map-url NexusUI.min.map \
  --compress warnings=false
